/*
 *
 * Copyright SHMsoft, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.freeeed.ui;

import org.freeeed.main.FreeEedMain;
import org.freeeed.main.ParameterProcessing;
import org.freeeed.main.Version;
import org.freeeed.services.*;
import org.freeeed.util.FolderOpener;
import org.freeeed.util.LogFactory;
import org.freeeed.util.OsUtil;

import javax.swing.*;
import java.awt.*;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.net.URI;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.logging.Logger;

/**
 * @author mark
 */
public class FreeEedUI extends javax.swing.JFrame {

    private final static Logger LOGGER = LogFactory.getLogger(FreeEedUI.class.getName());
    public static String defaultTitle = ParameterProcessing.APP_NAME + ParameterProcessing.TM
            + " v" + Version.getVersionNumber() + " - e-Discovery, Search, and AI Platform";

    private static FreeEedUI instance;

    public static FreeEedUI getInstance() {
        return instance;
    }

    /**
     * Creates new form Main
     */
    public FreeEedUI() {
        LOGGER.info("Starting " + Version.getVersionAndBuild());
        LOGGER.info("System check:");
        try {
            com.formdev.flatlaf.FlatLightLaf.setup();
        } catch (Exception e) {
            LOGGER.severe("UI ERROR " + e.getMessage());
        }
        String systemCheckErrors = OsUtil.systemCheck();
        if (!systemCheckErrors.isEmpty()) {
            SystemCheckUI ui = new SystemCheckUI(this, true);
            ui.setSystemErrorsText(systemCheckErrors);
            ui.setVisible(true);
        }
        ArrayList<String> systemReport = SystemSummary.getSystemSummary();
        for (String stat : systemReport) {
            LOGGER.info(stat);
        }
        try {
            Mode.load();
            Settings.load();
        } catch (Exception e) {
            LOGGER.severe("Problem initializing internal db");
        }

        initComponents();
    }

    public void setInstance(FreeEedUI aInstance) {
        instance = aInstance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        jSeparator1 = new javax.swing.JSeparator();
        statusLabel = new javax.swing.JLabel();
        mainMenu = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        menuItemProjects = new javax.swing.JMenuItem();
        menuItemHosting = new javax.swing.JMenuItem();
        menuItemBackup = new javax.swing.JMenuItem();
        menuItemSeparator = new javax.swing.JPopupMenu.Separator();
        menuItemExit = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        menuItemProjectOptions = new javax.swing.JMenuItem();
        processMenu = new javax.swing.JMenu();
        InventoryMenuItem = new javax.swing.JMenuItem();
        stageMenuItem = new javax.swing.JMenuItem();
        processMenuItem = new javax.swing.JMenuItem();
        processSeparator = new javax.swing.JPopupMenu.Separator();
        historyMenuItem = new javax.swing.JMenuItem();
        reviewMenu = new javax.swing.JMenu();
        menuItemOutputFolder = new javax.swing.JMenuItem();
        menuItemOpenSearchUI = new javax.swing.JMenuItem();
        menuItemOpenRawSolr = new javax.swing.JMenuItem();
        settingsMenu = new javax.swing.JMenu();
        programSettingsMenuItem = new javax.swing.JMenuItem();
        premiumMenu = new javax.swing.JMenu();
        backupRestoreMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        manualMenuItem = new javax.swing.JMenuItem();
        changelogMenuItem = new javax.swing.JMenuItem();
        licenseMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FreeEed - Graphical User Interface");
        setResizable(false);
        setSize(new java.awt.Dimension(670, 500));

        statusLabel.setBackground(java.awt.Color.lightGray);
        statusLabel.setText("No project open.");
        statusLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 5, 2, 5));

        fileMenu.setText("File");
        fileMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileMenuActionPerformed(evt);
            }
        });

        menuItemProjects.setText("Projects");
        menuItemProjects.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemProjectsActionPerformed(evt);
            }
        });
        fileMenu.add(menuItemProjects);

        menuItemHosting.setText("Edition");
        menuItemHosting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemHostingActionPerformed(evt);
            }
        });
        fileMenu.add(menuItemHosting);

        menuItemBackup.setText("Backup/Restore");
        menuItemBackup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemBackupActionPerformed(evt);
            }
        });
        fileMenu.add(menuItemBackup);
        fileMenu.add(menuItemSeparator);

        menuItemExit.setText("Exit");
        menuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemExitActionPerformed(evt);
            }
        });
        fileMenu.add(menuItemExit);

        mainMenu.add(fileMenu);

        editMenu.setText("Edit");

        menuItemProjectOptions.setText("Project options");
        menuItemProjectOptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemProjectOptionsActionPerformed(evt);
            }
        });
        editMenu.add(menuItemProjectOptions);

        mainMenu.add(editMenu);

        processMenu.setText("Process");
        processMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processMenuActionPerformed(evt);
            }
        });

        InventoryMenuItem.setText("Inventory inputs");
        InventoryMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InventoryMenuItemActionPerformed(evt);
            }
        });
        processMenu.add(InventoryMenuItem);

        stageMenuItem.setText("Stage files");
        stageMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stageMenuItemActionPerformed(evt);
            }
        });
        processMenu.add(stageMenuItem);

        processMenuItem.setText("Process staged files");
        processMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processMenuItemActionPerformed(evt);
            }
        });
        processMenu.add(processMenuItem);
        processMenu.add(processSeparator);

        historyMenuItem.setText("System");
        historyMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historyMenuItemActionPerformed(evt);
            }
        });
        processMenu.add(historyMenuItem);

        mainMenu.add(processMenu);

        reviewMenu.setText("Review");

        menuItemOutputFolder.setText("See output files");
        menuItemOutputFolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemOutputFolderActionPerformed(evt);
            }
        });
        reviewMenu.add(menuItemOutputFolder);

        menuItemOpenSearchUI.setText("Go to review");
        menuItemOpenSearchUI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemOpenSearchUIActionPerformed(evt);
            }
        });
        reviewMenu.add(menuItemOpenSearchUI);

        menuItemOpenRawSolr.setText("Open SOLR index");
        menuItemOpenRawSolr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemOpenRawSolrActionPerformed(evt);
            }
        });
        reviewMenu.add(menuItemOpenRawSolr);

        mainMenu.add(reviewMenu);

        settingsMenu.setText("Settings");

        programSettingsMenuItem.setText("Program settings");
        programSettingsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                programSettingsMenuItemActionPerformed(evt);
            }
        });
        settingsMenu.add(programSettingsMenuItem);

        mainMenu.add(settingsMenu);

        premiumMenu.setText("Backup/Restore");

        backupRestoreMenuItem.setText("Backup/Restore");
        backupRestoreMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backupRestoreMenuItemActionPerformed(evt);
            }
        });
        premiumMenu.add(backupRestoreMenuItem);

        mainMenu.add(premiumMenu);

        helpMenu.setText("Help");

        manualMenuItem.setText("Manual");
        manualMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manualMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(manualMenuItem);

        changelogMenuItem.setText("Changelog");
        changelogMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changelogMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(changelogMenuItem);

        licenseMenuItem.setText("License / EULA...");
        licenseMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                licenseMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(licenseMenuItem);

        aboutMenuItem.setText("About");
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(aboutMenuItem);

        mainMenu.add(helpMenu);

        setJMenuBar(mainMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 658, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(statusLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(409, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusLabel)
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
        new AboutDialog(this, true).setVisible(true);
    }//GEN-LAST:event_aboutMenuItemActionPerformed

    private void manualMenuItemActionPerformed(java.awt.event.ActionEvent evt) {
        UtilUI.openBrowser(FreeEedUI.getInstance(), "https://github.com/shmsoft/FreeEed/wiki");
    }

    private void menuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemExitActionPerformed
        try {
            exitApp();
        } catch (Exception e) {
            LOGGER.severe("Error saving project");
            JOptionPane.showMessageDialog(this, "Application error " + e.getMessage());
        }
    }//GEN-LAST:event_menuItemExitActionPerformed

    private void menuItemProjectsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemProjectsActionPerformed
        openProject();
    }//GEN-LAST:event_menuItemProjectsActionPerformed

    private void stageMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stageMenuItemActionPerformed
        stageProject();
    }//GEN-LAST:event_stageMenuItemActionPerformed

    private void processMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processMenuItemActionPerformed
        processProject();
    }//GEN-LAST:event_processMenuItemActionPerformed

    private void historyMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historyMenuItemActionPerformed
        showHistory();
    }//GEN-LAST:event_historyMenuItemActionPerformed

    private void menuItemProjectOptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemProjectOptionsActionPerformed
        showProcessingOptions();
    }//GEN-LAST:event_menuItemProjectOptionsActionPerformed

    private void menuItemOpenRawSolrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemOpenRawSolrActionPerformed
        openSolr();
    }//GEN-LAST:event_menuItemOpenRawSolrActionPerformed

    private void menuItemOpenSearchUIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemOpenSearchUIActionPerformed
        openReviewUI();
    }//GEN-LAST:event_menuItemOpenSearchUIActionPerformed

    private void menuItemOutputFolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemOutputFolderActionPerformed
        try {
            openOutputFolder();
        } catch (IOException e) {
            LOGGER.severe("Could not open folder");
            JOptionPane.showMessageDialog(this, "Something is wrong with the OS, please open the output folder manually");
        }
    }//GEN-LAST:event_menuItemOutputFolderActionPerformed

    private void menuItemBackupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemBackupActionPerformed
        openBackupUtility();
    }//GEN-LAST:event_menuItemBackupActionPerformed

    private void menuItemHostingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemHostingActionPerformed
        openHostingDialog();
    }//GEN-LAST:event_menuItemHostingActionPerformed

    private void fileMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileMenuActionPerformed
        openBackupUtility();
    }//GEN-LAST:event_fileMenuActionPerformed

    private void programSettingsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_programSettingsMenuItemActionPerformed
        openProgramSettings();
    }//GEN-LAST:event_programSettingsMenuItemActionPerformed

    private void backupRestoreMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backupRestoreMenuItemActionPerformed
        openBackupUtility();
    }//GEN-LAST:event_backupRestoreMenuItemActionPerformed

    private void changelogMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changelogMenuItemActionPerformed
        new WhatsNewDialog().show(this);
        // UtilUI.openBrowser(FreeEedUI.getInstance(), "https://github.com/shmsoft/FreeEed/wiki/Changelog");
    }//GEN-LAST:event_changelogMenuItemActionPerformed

    private void licenseMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_licenseMenuItemActionPerformed
        openLicenseDialog();
    }//GEN-LAST:event_licenseMenuItemActionPerformed

    private void processMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_processMenuActionPerformed

    private void InventoryMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InventoryMenuItemActionPerformed
        inventoryProject();
    }//GEN-LAST:event_InventoryMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        // the first argument is the app type
        // it can be M for med, or E for no argument
        String appType = args.length > 0 ? args[0] : "E";
        ParameterProcessing.setAppType(appType);

        java.awt.EventQueue.invokeLater(() -> {
            if (!shouldProceedAfterEditionDialog()) {
                return; // user cancelled
            }
            FreeEedUI ui = new FreeEedUI();
            ui.setInstance(ui);
            ui.setVisible(true);
        });
    }

    /**
     * @return true if app should continue to main UI, false if user cancelled.
     */
    private static boolean shouldProceedAfterEditionDialog() {
        try {
            // Startup occurs before FreeEedUI() constructor, so Settings.load() hasn't run yet.
            // Load DB-backed settings here, otherwise edition_remember is not available.
            try {
                Mode.load();
            } catch (Exception ignored) {
                // best-effort; Settings may still load
            }
            try {
                Settings.load();
            } catch (Exception ignored) {
                // best-effort; we'll fall back to defaults
            }

            Settings settings = Settings.getSettings();

            // If user asked to remember choice, skip dialog.
            if (settings.isEditionRemembered()) {
                return true;
            }

            // Modal dialog; blocks until closed.
            FreeEedEdition dialog = new FreeEedEdition(null, true);
            dialog.setVisible(true);

            if (dialog.isCancelled()) {
                return false;
            }

            // Persist selection when user clicks Continue.
            // If 'Remember' is checked, we save both remember flag and selection.
            // If not checked, we clear the remember flag (and stored selection) so dialog shows next launch.
            if (dialog.isRememberChoice()) {
                settings.setEditionRemembered(true);
                settings.setEditionSelected(dialog.getSelectedEdition());
            } else {
                settings.setEditionRemembered(false);
                settings.setEditionSelected("");
            }
            settings.save();

            return true;
        } catch (Exception e) {
            // If anything goes wrong, fail open (let user into app)
            LOGGER.warning("Could not process edition dialog settings: " + e.getMessage());
            return true;
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem InventoryMenuItem;
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem backupRestoreMenuItem;
    private javax.swing.JMenuItem changelogMenuItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem historyMenuItem;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JMenuItem licenseMenuItem;
    private javax.swing.JMenuBar mainMenu;
    private javax.swing.JMenuItem manualMenuItem;
    private javax.swing.JMenuItem menuItemBackup;
    private javax.swing.JMenuItem menuItemExit;
    private javax.swing.JMenuItem menuItemHosting;
    private javax.swing.JMenuItem menuItemOpenRawSolr;
    private javax.swing.JMenuItem menuItemOpenSearchUI;
    private javax.swing.JMenuItem menuItemOutputFolder;
    private javax.swing.JMenuItem menuItemProjectOptions;
    private javax.swing.JMenuItem menuItemProjects;
    private javax.swing.JPopupMenu.Separator menuItemSeparator;
    private java.awt.Panel panel1;
    private javax.swing.JMenu premiumMenu;
    private javax.swing.JMenu processMenu;
    private javax.swing.JMenuItem processMenuItem;
    private javax.swing.JPopupMenu.Separator processSeparator;
    private javax.swing.JMenuItem programSettingsMenuItem;
    private javax.swing.JMenu reviewMenu;
    private javax.swing.JMenu settingsMenu;
    private javax.swing.JMenuItem stageMenuItem;
    private javax.swing.JLabel statusLabel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setVisible(boolean b) {
        if (b) {
            myInitComponents();
            applyEditionFeatureGates();
        }
        super.setVisible(b);
    }

    /**
     * Hide/disable premium features based on remembered or current edition selection.
     */

    private JPanel welcomePanel;
    private static final Color STEP_COMPLETE = new Color(76, 175, 80);
    private static final Color STEP_CURRENT = new Color(33, 150, 243);
    private static final Color STEP_FUTURE = new Color(189, 189, 189);
    private static final Color ARROW_COLOR = new Color(180, 180, 180);
    private static final String[] STEP_LABELS = {"Project", "Inventory", "Stage", "Process", "Review"};
    private static final String[] STEP_DESCRIPTIONS = {
            "Create or open a project and add data",
            "Inventory input files",
            "Stage files for processing",
            "Process staged files",
            "Review processed results"
    };
    private JLabel[] stepCircles;
    private JLabel[] stepLabels;
    private JLabel[] arrowLabels;
    private JLabel stepDescription;

    private void myInitComponents() {
        addWindowListener(new FrameListener());
        setResizable(true);
        setBounds(64, 40, 640, 400);
        setLocationRelativeTo(null);
        setTitle(defaultTitle);

        // Replace GroupLayout with BorderLayout so we can use the main area
        Container content = getContentPane();
        content.removeAll();
        content.setLayout(new BorderLayout());

        // Bottom: separator + status
        JPanel bottomPanel = new JPanel();
        bottomPanel.setLayout(new BoxLayout(bottomPanel, BoxLayout.Y_AXIS));
        bottomPanel.add(jSeparator1);
        JPanel statusPanel = new JPanel(new FlowLayout(FlowLayout.LEFT, 5, 2));
        statusPanel.add(statusLabel);
        bottomPanel.add(statusPanel);
        content.add(bottomPanel, BorderLayout.SOUTH);

        // Center: welcome panel with stepper
        welcomePanel = createWelcomePanel();
        content.add(welcomePanel, BorderLayout.CENTER);

        content.revalidate();
        content.repaint();
        refreshStepper();
    }

    private JPanel createWelcomePanel() {
        JPanel panel = new JPanel(new GridBagLayout());
        panel.setBackground(Color.WHITE);
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.gridwidth = GridBagConstraints.REMAINDER;
        gbc.insets = new Insets(15, 0, 5, 0);

        JLabel titleLabel = new JLabel("Welcome to FreeEed");
        titleLabel.setFont(new Font("SansSerif", Font.BOLD, 20));
        titleLabel.setForeground(new Color(60, 60, 60));
        panel.add(titleLabel, gbc);

        gbc.gridy++;
        gbc.insets = new Insets(2, 0, 25, 0);
        JLabel subtitleLabel = new JLabel("e-Discovery, Search, and AI Platform");
        subtitleLabel.setFont(new Font("SansSerif", Font.PLAIN, 13));
        subtitleLabel.setForeground(Color.GRAY);
        panel.add(subtitleLabel, gbc);

        // Stepper row
        gbc.gridy++;
        gbc.gridwidth = GridBagConstraints.REMAINDER;
        gbc.insets = new Insets(0, 0, 20, 0);
        JPanel stepperRow = createStepperRow();
        panel.add(stepperRow, gbc);

        // Step description
        gbc.gridy++;
        gbc.insets = new Insets(0, 0, 20, 0);
        stepDescription = new JLabel(" ");
        stepDescription.setFont(new Font("SansSerif", Font.ITALIC, 13));
        stepDescription.setForeground(Color.GRAY);
        panel.add(stepDescription, gbc);

        // Quick action buttons
        gbc.gridy++;
        gbc.insets = new Insets(5, 0, 5, 0);
        JButton openBtn = new JButton("Open Project");
        openBtn.setFont(new Font("SansSerif", Font.PLAIN, 13));
        openBtn.addActionListener(e -> openProject());
        panel.add(openBtn, gbc);

        gbc.gridy++;
        gbc.insets = new Insets(3, 0, 5, 0);
        JButton newBtn = new JButton("New Project");
        newBtn.setFont(new Font("SansSerif", Font.PLAIN, 13));
        newBtn.addActionListener(e -> {
            try {
                Project project = org.freeeed.db.DbLocalUtils.createNewProject();
                Project.setCurrentProject(project);
                updateStatus();
                showProcessingOptions();
            } catch (Exception ex) {
                LOGGER.severe("Problem creating new project: " + ex.getMessage());
            }
        });
        panel.add(newBtn, gbc);

        return panel;
    }

    private JPanel createStepperRow() {
        JPanel row = new JPanel(new FlowLayout(FlowLayout.CENTER, 0, 0));
        row.setBackground(Color.WHITE);

        stepCircles = new JLabel[5];
        stepLabels = new JLabel[5];
        arrowLabels = new JLabel[4];

        Runnable[] actions = {
                () -> openProject(),
                () -> inventoryProject(),
                () -> stageProject(),
                () -> processProject(),
                () -> {
                    try { openOutputFolder(); } catch (IOException ex) {
                        LOGGER.severe("Could not open folder");
                    }
                }
        };

        for (int i = 0; i < 5; i++) {
            JPanel stepPanel = new JPanel();
            stepPanel.setLayout(new BoxLayout(stepPanel, BoxLayout.Y_AXIS));
            stepPanel.setBackground(Color.WHITE);
            stepPanel.setAlignmentY(Component.CENTER_ALIGNMENT);

            // Circle with number
            JLabel circle = new JLabel(String.valueOf(i + 1), SwingConstants.CENTER) {
                @Override
                public Dimension getPreferredSize() {
                    return new Dimension(36, 36);
                }
                @Override
                public Dimension getMinimumSize() {
                    return getPreferredSize();
                }
                @Override
                public Dimension getMaximumSize() {
                    return getPreferredSize();
                }
                @Override
                protected void paintComponent(Graphics g) {
                    Graphics2D g2 = (Graphics2D) g.create();
                    g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                    g2.setColor(getBackground());
                    g2.fillOval(0, 0, getWidth() - 1, getHeight() - 1);
                    g2.dispose();
                    super.paintComponent(g);
                }
            };
            circle.setOpaque(false);
            circle.setBackground(STEP_FUTURE);
            circle.setForeground(Color.WHITE);
            circle.setFont(new Font("SansSerif", Font.BOLD, 14));
            circle.setHorizontalAlignment(SwingConstants.CENTER);
            circle.setAlignmentX(Component.CENTER_ALIGNMENT);
            stepCircles[i] = circle;

            // Label below circle
            JLabel label = new JLabel(STEP_LABELS[i]);
            label.setFont(new Font("SansSerif", Font.PLAIN, 11));
            label.setForeground(STEP_FUTURE);
            label.setAlignmentX(Component.CENTER_ALIGNMENT);
            stepLabels[i] = label;

            stepPanel.add(Box.createVerticalGlue());
            stepPanel.add(circle);
            stepPanel.add(Box.createVerticalStrut(4));
            stepPanel.add(label);
            stepPanel.add(Box.createVerticalGlue());

            // Make clickable
            final int stepIndex = i;
            final Runnable action = actions[i];
            stepPanel.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
            stepPanel.addMouseListener(new java.awt.event.MouseAdapter() {
                @Override
                public void mouseClicked(java.awt.event.MouseEvent e) {
                    action.run();
                }
                @Override
                public void mouseEntered(java.awt.event.MouseEvent e) {
                    stepDescription.setText(STEP_DESCRIPTIONS[stepIndex]);
                }
                @Override
                public void mouseExited(java.awt.event.MouseEvent e) {
                    showCurrentStepDescription();
                }
            });

            row.add(stepPanel);

            // Arrow between steps
            if (i < 4) {
                JLabel arrow = new JLabel("  \u279C  ");
                arrow.setFont(new Font("SansSerif", Font.PLAIN, 18));
                arrow.setForeground(ARROW_COLOR);
                arrowLabels[i] = arrow;
                row.add(arrow);
            }
        }

        return row;
    }

    private void showCurrentStepDescription() {
        int current = getCurrentStep();
        if (current < 5) {
            stepDescription.setText(STEP_DESCRIPTIONS[current]);
        } else {
            stepDescription.setText("All steps complete!");
        }
    }

    private int getCurrentStep() {
        Project project = Project.getCurrentProject();
        if (project == null || project.isEmpty()) return 0;
        if (project.getInputs().length == 0) return 0;
        // Check inventory
        File inventoryFile = new File(project.getInventoryFileName());
        if (!inventoryFile.exists()) return 1;
        // Check staging
        File stagingDir = new File(project.getStagingDir());
        if (!stagingDir.exists() || stagingDir.list() == null || stagingDir.list().length <= 1) return 2;
        // Check results
        String resultsDir = project.getResultsDir();
        if (resultsDir == null) return 3;
        File resultsFolder = new File(resultsDir);
        if (!resultsFolder.exists() || resultsFolder.list() == null || resultsFolder.list().length == 0) return 3;
        return 4;
    }

    public void refreshStepper() {
        if (stepCircles == null) return;
        int current = getCurrentStep();
        for (int i = 0; i < 5; i++) {
            Color color;
            if (i < current) {
                color = STEP_COMPLETE;
                stepCircles[i].setText("\u2713"); // checkmark
            } else if (i == current) {
                color = STEP_CURRENT;
                stepCircles[i].setText(String.valueOf(i + 1));
            } else {
                color = STEP_FUTURE;
                stepCircles[i].setText(String.valueOf(i + 1));
            }
            stepCircles[i].setBackground(color);
            stepLabels[i].setForeground(color);
            stepLabels[i].setFont(new Font("SansSerif", i == current ? Font.BOLD : Font.PLAIN, 11));
        }
        // Color arrows between completed steps
        for (int i = 0; i < 4; i++) {
            arrowLabels[i].setForeground(i < current ? STEP_COMPLETE : ARROW_COLOR);
        }
        showCurrentStepDescription();
        welcomePanel.repaint();
    }

    private void exitApp() throws Exception {
        if (!isExitAllowed()) {
            return;
        }
        Settings.getSettings().save();
        setVisible(false);
        System.exit(0);
    }

    private boolean isExitAllowed() {
        return true;
    }

    private void openProject() {
        ProjectsUI dialog = new ProjectsUI(this, true);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
    }

    public void openProject(File selectedFile) {
        Project project = Project.loadFromFile(selectedFile);
        project.setProjectFilePath(selectedFile.getPath());
        updateStatus();
        LOGGER.finest("Opened project file: " + selectedFile.getPath());
        Settings settings = Settings.getSettings();
        settings.addRecentProject(selectedFile.getPath());
        showProcessingOptions();
    }

    private class ProjectFilter extends javax.swing.filechooser.FileFilter {

        @Override
        public boolean accept(File file) {
            String filename = file.getName();
            return filename.endsWith(".project") || file.isDirectory();
        }

        @Override
        public String getDescription() {
            return "Project files";
        }
    }

    public void updateTitle(String title) {
        if (title != null) {
            setTitle(ParameterProcessing.APP_NAME + ParameterProcessing.TM + " - " + title);
        } else {
            setTitle(ParameterProcessing.APP_NAME + ParameterProcessing.TM);
        }
    }

    public void updateStatus() {
        Project project = Project.getCurrentProject();
        if (project == null || project.isEmpty()) {
            statusLabel.setText("No project open.");
            return;
        }
        StringBuilder sb = new StringBuilder();
        String name = project.getProjectName();
        String code = project.getProjectCode();
        if (code != null && !code.isEmpty()) {
            sb.append(code);
        }
        if (name != null && !name.isEmpty()) {
            if (sb.length() > 0) sb.append(" - ");
            sb.append(name);
        }
        int inputCount = project.getInputs().length;
        sb.append(" | ").append(inputCount).append(inputCount == 1 ? " input" : " inputs");
        statusLabel.setText(sb.toString());
        refreshStepper();
    }

    public void showProcessingOptions() {
        if (Project.getCurrentProject().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please create or open a project first");
            return;
        }
        ProjectUI dialog = new ProjectUI(this, true);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
    }

    private void stageProject() {
        Project project = Project.getCurrentProject();
        if (project.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please create or open a project first");
            return;
        }
        // check for empty input directories
        String[] dirs = project.getInputs();
        if (dirs.length == 0) {
            JOptionPane.showMessageDialog(rootPane, "You selected no data to stage");
            return;
        }
        for (String dir : dirs) {
            File file = new File(dir);
            if (file.isDirectory() && file.list().length == 0) {
                JOptionPane.showMessageDialog(rootPane, "Some of the directories you are trying to stage are empty. "
                        + "\\It does not make sense to stage them and may lead to confusion."
                        + "\\Please check the project directories");
                return;
            }
        }
        try {
            FreeEedMain.getInstance().runStagePackageInput();
        } catch (Exception e) {
            LOGGER.severe("Error staging project");
        }
    }

    private void runProcessing() throws IllegalStateException {
        Project project = Project.getCurrentProject();
        if (project.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please create or open a project first");
            return;
        }
        project.setEnvironment(Project.ENV_LOCAL);
        FreeEedMain mainInstance = FreeEedMain.getInstance();
        if (new File(project.getResultsDir()).exists()) {
            // in most cases, it won't already exist, but just in case
            try {
                Util.deleteDirectory(new File(project.getResultsDir()));
            } catch (Exception e) {
                throw new IllegalStateException(e.getMessage());
            }
        }
        String processWhere = project.getProcessWhere();
        if (processWhere != null) {
            mainInstance.runProcessing(processWhere);
        } else {
            throw new IllegalStateException("No processing option selected.");
        }
    }

    private void showHistory() {
        SystemUI ui = new SystemUI();
        ui.setVisible(true);
    }

    private boolean areResultsPresent() {
        try {
            Project project = Project.getCurrentProject();
            if (project == null || project.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please open a project first");
                return false;
            }
            boolean success = Review.deliverFiles();
            if (!success) {
                JOptionPane.showMessageDialog(this, "No results yet");
                return false;
            }
        } catch (IOException e) {
            LOGGER.warning("Results present? Problem!");
            return false;
        }
        return true;
    }

    private void openOutputFolder() throws IOException {
        if (!areResultsPresent()) {
            return;
        }
        String resultsFolder = Project.getCurrentProject().getResultsDir();
        new FolderOpener(resultsFolder).execute();
    }

    class FrameListener extends WindowAdapter {

        @Override
        public void windowClosing(WindowEvent e) {
            try {
                Settings.getSettings().save();
            } catch (Exception ex) {
                LOGGER.severe("Error saving project");
                JOptionPane.showMessageDialog(null, "Application error " + ex.getMessage());
            }

        }
    }

    private void openWiki() {
        Settings settings = Settings.getSettings();
        String url = settings.getManualPage();
        UtilUI.openBrowser(this, url);
    }

    private void openProgramSettings() {
        ProgramSettingsUI programSettingsUI = new ProgramSettingsUI(this, true);
        programSettingsUI.setVisible(true);
    }

    private void openSolr() {
        Settings settings = Settings.getSettings();
        String url = settings.getSolrEndpoint() + "/solr/admin";
        UtilUI.openBrowser(this, url);
    }

    private void openReviewUI() {
        Settings settings = Settings.getSettings();
        String url = settings.getReviewEndpoint();
        UtilUI.openBrowser(this, url);
    }

    public void processProject() {
        try {
            runProcessing();
        } catch (IllegalStateException e) {
            JOptionPane.showMessageDialog(this, "There were some problems with processing, \""
                    + e.getMessage() + "\n"
                    + "please check console output");
        }
    }

    private void openModeUI() {
        RunModeUI ui = new RunModeUI(this, true);
        ui.setVisible(true);
    }

    private void openWordCloudUI() {
        Project project = Project.getCurrentProject();
        if (project.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Please open a project first");
            return;
        }
    }

    private void startSolr() {
        String command = "cd freeeed-solr/example; java -Xmx1024M -jar start.jar &";
        try {
            OsUtil.runCommand(command);
        } catch (IOException e) {
            LOGGER.severe("Problem starting SOLR");
        }
    }

    private void openBackupUtility() {
        if (OsUtil.isLinux()) {
            openBrowserToBackup();
        }
        String premiumFeatures = Settings.getSettings().getPremiumFeaturesDirectory();
        java.nio.file.Path backupUtilityPath = java.nio.file.Paths.get(
                        (premiumFeatures == null || premiumFeatures.trim().isEmpty()) ? "" : premiumFeatures.trim()
                ).resolve("releases")
                .resolve(OsUtil.whichOs());

        String backupUtility = backupUtilityPath.toString();

        LOGGER.info("Backup utility path: " + backupUtility + "/BackupRestore");
        //prepareBackupSettings(backupUtility);
        if (backupUtility == null || backupUtility.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Backup utility path is not configured");
            return;
        }

        File targetDir = new File(backupUtility);
        if (!targetDir.exists() || !targetDir.isDirectory()) {
            JOptionPane.showMessageDialog(this, "Backup utility directory not found: " + targetDir.getPath());
            return;
        }
        // Choose executable name per OS
        String launcherName = OsUtil.isWindows() ? "BackupRestore.exe" : "BackupRestore";

        // OS-safe join
        java.nio.file.Path scriptPath = targetDir.toPath().resolve(launcherName);
        String script = scriptPath.toString();
        String cmd = script;
        try {
            OsUtil.runCommandDetached(cmd);
            LOGGER.info("Started BackupRestore utility:");
        } catch (IOException e) {
            LOGGER.severe("Problem starting BackupRestore utility: " + e.getMessage());
            JOptionPane.showMessageDialog(this,
                    "Could not start BackupRestore utility: " + e.getMessage());
        }
    }

    private void openBrowserToBackup() {
        try {
            URI uri = new URI("http://localhost:9000");

            if (Desktop.isDesktopSupported()) {
                Desktop desktop = Desktop.getDesktop();
                if (desktop.isSupported(Desktop.Action.BROWSE)) {
                    desktop.browse(uri);
                    return;
                }
            }

            // Linux fallback
            OsUtil.runCommandDetached("xdg-open " + uri);

        } catch (Exception e) {
            LOGGER.warning("Could not open browser automatically: " + e.getMessage());
        }
    }

    // helper to minimally escape backslashes and quotes for JSON strings
    private static String escapeForJson(String s) {
        if (s == null) {
            return "";
        }
        return s.replace("\\", "\\\\").replace("\"", "\\\"");
    }

    private void openHostingDialog() {
        FreeEedEdition ui = new FreeEedEdition(this, true);
        ui.setVisible(true);
        // refresh gates in case edition changed
        applyEditionFeatureGates();
    }

    private void applyEditionFeatureGates() {
        boolean isOpenSource = Settings.getSettings().isOpenSourceEdition();
        menuItemBackup.setEnabled(!isOpenSource);
    }
    public final class WhatsNewDialog {

        private static final String FULL_CHANGELOG_URL =
                "https://github.com/shmsoft/FreeEed/wiki/Changelog";

        public void show(JFrame parent) {
            try {
                String full = loadChangelog();
                String latest = extractLatestSection(full);

                JEditorPane editorPane = new JEditorPane();
                setWhatsNewContent(editorPane, latest);

                JScrollPane scroll = new JScrollPane(editorPane);
                scroll.setPreferredSize(new Dimension(520, 300));

                Object[] options = {
                        "View full changelog",
                        "Close"
                };

                int choice = JOptionPane.showOptionDialog(
                        parent,
                        scroll,
                        "What’s New",
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.INFORMATION_MESSAGE,
                        null,
                        options,
                        options[1]
                );

                if (choice == 0) {
                    UtilUI.openBrowser(parent, FULL_CHANGELOG_URL);
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(
                        parent,
                        "Unable to load changelog: " + e.getMessage(),
                        "Error",
                        JOptionPane.ERROR_MESSAGE
                );
            }
        }
    }
    public static String loadChangelog() throws IOException {

        // 1️⃣ Try classpath (inside JAR)
        String[] resourceCandidates = {
                "CHANGELOG.md",
                "/CHANGELOG.md",
                "docs/CHANGELOG.md",
                "/docs/CHANGELOG.md"
        };

        ClassLoader cl = WhatsNewDialog.class.getClassLoader();

        for (String resource : resourceCandidates) {
            try (InputStream is = cl.getResourceAsStream(resource.replaceFirst("^/", ""))) {
                if (is != null) {
                    return new String(is.readAllBytes(), StandardCharsets.UTF_8);
                }
            }
        }

        // 2️⃣ Try filesystem (dev mode fallback)
        Path cwd = Paths.get("").toAbsolutePath().normalize();

        Path[] candidates = new Path[] {
                cwd.resolve("CHANGELOG.md"),
                cwd.resolve("docs").resolve("CHANGELOG.md"),
                cwd.getParent() != null ? cwd.getParent().resolve("CHANGELOG.md") : null,
                cwd.resolve("..").resolve("CHANGELOG.md").normalize(),
                cwd.resolve("..").resolve("..").resolve("CHANGELOG.md").normalize()
        };

        for (Path p : candidates) {
            if (p != null && Files.isRegularFile(p)) {
                return Files.readString(p, StandardCharsets.UTF_8);
            }
        }

        return "Changelog not found.\n\nWorking directory: " + cwd;
    }
    public static String extractLatestSection(String changelog) {
        if (changelog == null || changelog.isBlank()) {
            return "";
        }

        String s = changelog.replace("\r\n", "\n").replace("\r", "\n").trim();

        // Split into lines and find the first "Version ..." line (optionally with markdown header prefix).
        String[] lines = s.split("\n", -1);

        int start = -1;
        for (int i = 0; i < lines.length; i++) {
            String t = lines[i].trim();
            // Accept: "Version 10.7.2" OR "## Version 10.7.2" OR "### Version 10.7.2"
            if (t.matches("^(#{2,3}\\s+)?Version\\s+\\S+.*$")) {
                start = i;
                break;
            }
        }

        if (start < 0) {
            return s;
        }

        int end = lines.length;
        for (int i = start + 1; i < lines.length; i++) {
            String t = lines[i].trim();
            if (t.matches("^(#{2,3}\\s+)?Version\\s+\\S+.*$")) {
                end = i;
                break;
            }
        }

        StringBuilder out = new StringBuilder();
        for (int i = start; i < end; i++) {
            out.append(lines[i]).append('\n');
        }

        return out.toString().trim();
    }

    // Convert a small subset of Markdown used in CHANGELOG.md into HTML for Swing.
    static String markdownToHtml(String md) {
        if (md == null) return "<html><body></body></html>";

        String s = md.replace("\r\n", "\n").replace("\r", "\n").trim();

        // Escape HTML first
        s = s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;");

        StringBuilder html = new StringBuilder(1024);
        html.append("<html><body style='font-family:sans-serif;font-size:12px;'>");

        boolean inUl = false;

        for (String rawLine : s.split("\n", -1)) {
            String line = rawLine.trim();
            if (line.isEmpty()) {
                if (inUl) {
                    html.append("</ul>");
                    inUl = false;
                }
                html.append("<br/>");
                continue;
            }

            // Headings
            if (line.startsWith("### ")) {
                if (inUl) {
                    html.append("</ul>");
                    inUl = false;
                }
                html.append("<h3 style='margin:8px 0 4px 0;'>")
                        .append(line.substring(4).trim())
                        .append("</h3>");
                continue;
            }
            if (line.startsWith("## ")) {
                if (inUl) {
                    html.append("</ul>");
                    inUl = false;
                }
                html.append("<h2 style='margin:8px 0 6px 0;'>")
                        .append(line.substring(3).trim())
                        .append("</h2>");
                continue;
            }
            if (line.startsWith("# ")) {
                if (inUl) {
                    html.append("</ul>");
                    inUl = false;
                }
                html.append("<h1 style='margin:8px 0 6px 0;'>")
                        .append(line.substring(2).trim())
                        .append("</h1>");
                continue;
            }

            // Bullets ("- " or "* ")
            if (line.startsWith("- ") || line.startsWith("* ")) {
                if (!inUl) {
                    html.append("<ul style='margin:4px 0 8px 18px;'>");
                    inUl = true;
                }
                html.append("<li>").append(line.substring(2).trim()).append("</li>");
                continue;
            }

            // Plain line
            if (inUl) {
                html.append("</ul>");
                inUl = false;
            }
            html.append("<div>").append(line).append("</div>");
        }

        if (inUl) {
            html.append("</ul>");
        }

        html.append("</body></html>");
        return html.toString();
    }
    private void openLicenseDialog() {
        try {
            String eulaText = loadEulaText();

            JEditorPane editorPane = new JEditorPane();
            editorPane.setContentType("text/plain");
            editorPane.setEditable(false);
            editorPane.setFont(new Font("SansSerif", Font.PLAIN, 12));
            editorPane.setText(eulaText);
            editorPane.setCaretPosition(0);

            JScrollPane scroll = new JScrollPane(editorPane);
            scroll.setPreferredSize(new Dimension(600, 400));

            JOptionPane.showMessageDialog(
                    this,
                    scroll,
                    "End User License Agreement (EULA)",
                    JOptionPane.INFORMATION_MESSAGE
            );

        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    this,
                    "Unable to load EULA: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }

    private static String loadEulaText() throws IOException {
        // 1. Try classpath (inside JAR)
        String[] resourceCandidates = {
                "EULA.txt",
                "/EULA.txt"
        };

        ClassLoader cl = FreeEedUI.class.getClassLoader();
        for (String resource : resourceCandidates) {
            try (InputStream is = cl.getResourceAsStream(resource.replaceFirst("^/", ""))) {
                if (is != null) {
                    return new String(is.readAllBytes(), StandardCharsets.UTF_8);
                }
            }
        }

        // 2. Try filesystem (dev mode / installed location)
        Path cwd = Paths.get("").toAbsolutePath().normalize();
        Path[] candidates = new Path[]{
                cwd.resolve("EULA.txt"),
                cwd.resolve("..").resolve("EULA.txt").normalize(),
                cwd.resolve("..").resolve("..").resolve("EULA.txt").normalize()
        };

        for (Path p : candidates) {
            if (p != null && Files.isRegularFile(p)) {
                return Files.readString(p, StandardCharsets.UTF_8);
            }
        }

        // 3. Try user's home config directory
        Path homeEula = Paths.get(System.getProperty("user.home"), ".freeeed", "EULA.txt");
        if (Files.isRegularFile(homeEula)) {
            return Files.readString(homeEula, StandardCharsets.UTF_8);
        }

        return "EULA file not found.\n\nWorking directory: " + cwd;
    }

    // Example usage inside your WhatsNewDialog setup after you compute `latestSection`:
    static void setWhatsNewContent(JEditorPane editorPane, String latestSectionMarkdown) {
        editorPane.setContentType("text/html");
        editorPane.setEditable(false);
        editorPane.putClientProperty(JEditorPane.HONOR_DISPLAY_PROPERTIES, Boolean.TRUE);
        editorPane.setText(markdownToHtml(latestSectionMarkdown));
        editorPane.setCaretPosition(0);
    }
    private void inventoryProject() {
        Project project = Project.getCurrentProject();
        if (project.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please create or open a project first");
            return;
        }
        // check for empty input directories
        String[] dirs = project.getInputs();
        if (dirs.length == 0) {
            JOptionPane.showMessageDialog(rootPane, "You selected no data to stage");
            return;
        }
        for (String dir : dirs) {
            File file = new File(dir);
            if (file.isDirectory() && file.list().length == 0) {
                JOptionPane.showMessageDialog(rootPane, "Some of the directories you are trying to stage are empty. "
                        + "\\It does not make sense to stage them and may lead to confusion."
                        + "\\Please check the project directories");
                return;
            }
        }
        try {
            FreeEedMain.getInstance().runInventoryInput();
        } catch (Exception e) {
            LOGGER.severe("Error staging project");
        }

    }
}
